interfearence:
    controller:
        state:
            # Publish all joint states ---------------------------------
            joint_state_controller:
                type: joint_state_controller/JointStateController
                publish_rate: 50
        sim:
            # Velocity Controllers -------------------------------------
            left_velocity_controller:
                type: effort_controllers/JointVelocityController
                joint: left_wheel_joint
                pid: {p: 0.2, i: 0.02, d: 0.000001, i_clamp_min: -10.0, i_clamp_max: 10.0}
            right_velocity_controller:
                type: effort_controllers/JointVelocityController
                joint: right_wheel_joint
                pid: {p: 0.2, i: 0.02, d: 0.000001, i_clamp_min: -10.0, i_clamp_max: 10.0}
        velocity:
            # Velocity Controllers -------------------------------------
            left_velocity_controller:
                type: effort_controllers/JointVelocityController
                joint: left_wheel_joint
                pid: {p: 4.0, i: 0.0, d: 0.00000, i_clamp_min: -10.0, i_clamp_max: 10.0}
            right_velocity_controller:
                type: effort_controllers/JointVelocityController
                joint: right_wheel_joint
                pid: {p: 4.0, i: 0.0, d: 0.00000, i_clamp_min: -10.0, i_clamp_max: 10.0}

        differential:
            # Differential drive controller ----------------------------
            differential_controller:
                type: diff_drive_controller/DiffDriveController
                left_wheel: left_wheel_joint
                right_wheel: right_wheel_joint
                pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
                twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
                publish_rate: 50
                # Adjust for manufacutring tolerances
                wheel_separation_multiplier: 1.0 
                # Adjust for manufacturing tolerances
                wheel_radius_multiplier: 1.0
                # Num. seconds with no command after which a 0 command 
                # is sent to the wheels
                cmd_vel_timeout: 1.0
                base_frame_id: base_link
                linear:
                    x:
                        has_velocity_limits: true
                        max_velocity: 2.5
                        has_acceleration_limits: true
                        max_acceleration: 10
                        has_jerk_limits: false
                        #max_jerk: 100
                angular:
                    z:
                        has_velocity_limits: false
                        #max_velocity: 0
                        has_acceleration_limits: false
                        #max_acceleration: 0
                        has_jerk_limits: false
                        #max_jerk_limit: 0
                enable_odom_tf: true
                odom_frame_id: odom
                publish_cmd: true

