interfearence:
    controller:
        state:
            # Publish all joint states ---------------------------------
            joint_state_controller:
                type: joint_state_controller/JointStateController
                publish_rate: 50
        velocity:
            # Velocity Controllers -------------------------------------
            left_velocity_controller:
                type: effort_controllers/JointVelocityController
                joint: left_wheel_joint
                pid: {p: 100.0, i: 0.0, d: 0.0}
            right_velocity_controller:
                type: effort_controllers/JointVelocityController
                joint: right_wheel_joint
                pid: {p: 100.0, i: 0.0, d: 0.0}
        
