joint_limits:
    left_wheel_joint:
        has_position_limits: false
        has_velocity_limits: true
        max_velocity: 83.776
        has_acceleration_limits: true
        max_acceleration: 1256.6667
        has_jerk_limits: true
        max_jerk: 100.0
        has_effort_limits: true
        max_effort: 2.0
    right_wheel_joint:
        has_position_limits: false
        has_velocity_limits: true
        max_velocity: 83.776
        has_acceleration_limits: true
        max_acceleration: 1256.6667
        has_jerk_limits: true
        max_jerk: 100.0
        has_effort_limits: true
        max_effort: 2.0
